include::_attributes.adoc[]


= Installing Tekton Chains for Image Signing

== Creating the CRD

. Configure Tekton Chains by running the below commands:
+
[source, role="execute"]
----
cd
cat <<EOF >> chains.yaml
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonChain
metadata:
  name: chain
spec:
  artifacts.oci.storage: oci
  artifacts.taskrun.format: in-toto
  artifacts.taskrun.storage: oci
  config: {}
  targetNamespace: openshift-pipelines
  transparency.enabled: true
EOF
oc apply -f chains.yaml
----
+
. Run the next command a few times to check if the deployment is available:
+
[source, role="execute"]
----
oc get deployment tekton-chains-controller -n openshift-pipelines
----
Wait for the *AVAILABLE* column to display *1*
+
[source]
----
NAME                       READY   UP-TO-DATE   AVAILABLE   AGE
tekton-chains-controller   1/1     1            1           106m
----

== Trigger the Pipeline

. Switch back to {codeserver_url}[Code Server]
. On the left side of the screen, under *IDE (WORKSPACE)*, you will find the *globex-ui* source code project.  Expand the *src* folder and click on *index.html*.
. On line *19* modify the *center* html element value from *Globex Update* to *Globex Signed*
. From the top menu, click *File > Save*
. Click the source control icon on the left side of the screen
. Notice that the *index.html* file is shown under the *Changes* section.  Click the *+* sign to the right of the file name.
This will add the file to the Git staging area.
. Next enter some text in the *Commit* text box, such as *globex update 2*, and click *Commit*.
This saves your changes to the local repository.
. Next click the *Sync Changes* button to push your change to the remote repository.
. Switch back to *Openshift* and click *Pipelines > Pipelines* from the left menu.  Ensure that your project is set to *ci*.
. Notice that another instance of your pipeline run has started.  Wait for it to complete.

== Examine pipeline
. Click on the pipeline.  The *acs-image-check* is now successful which means that your latest image is now signed with the *Cosign* private key.
. Click on *acs-deploy-check*.  You will see that there is a critical warning that there are no resource requests or limits set for your deployment.  We will fix this in the next section.

== Examine Quay
. Login to {quay_console_url}[Quay] with username {quay_admin_username} and password {quay_admin_password}.
. Under *REPOSITORIES*, click the repository *quayadmin / globex-ui*
. On the left side of the screen, click on the *Tags* icon.
. Observe that your image tags now have a black shield icon at the end.
. Hover over the icon for a tooltip to appear confirming your tag was signed with Cosign.